import random
import os
from faker import Faker

fake = Faker()

STATUSES = ["Active"] * 8 + ["Inactive"] * 2  # 80% Active, 20% Inactive

NUM_RECORDS = 100

used_names = set()


def unique_category_name():
    while True:
        name = fake.bs().title()
        if name not in used_names:
            used_names.add(name)
            return name


def escape_sql(s):
    return s.replace("'", "''")


lines = [
    "-- FundBridger FRA Category seed data (100 records)",
    "-- Generated by seed/seed_fra_category.py",
    "",
]

records = []
for i in range(NUM_RECORDS):
    name = unique_category_name()
    description = fake.sentence(nb_words=12)
    status = random.choice(STATUSES)

    sql = (
        f"INSERT INTO fra_category (\"categoryName\", \"categoryDescription\", \"categoryStatus\") "
        f"VALUES ('{escape_sql(name)}', '{escape_sql(description)}', '{status}');"
    )
    records.append(sql)

lines.extend(records)

output_path = os.path.join(os.path.dirname(__file__), "fra_category_seed.sql")
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("fra_category_seed.sql generated successfully.")
