import random
import os
import bcrypt
from faker import Faker

fake = Faker()

ROLES = ["User Admin", "Donee", "Platform Management", "Fund Raiser"]
STATUSES = ["Active"] * 8 + ["Inactive"] * 2  # 80% Active, 20% Inactive

NUM_RECORDS = 100

used_ids = set()
used_usernames = set()
used_emails = set()


def unique_user_id():
    while True:
        uid = random.randint(10000000, 99999999)
        if uid not in used_ids:
            used_ids.add(uid)
            return uid


def unique_username():
    while True:
        name = fake.user_name()
        if name not in used_usernames:
            used_usernames.add(name)
            return name


def unique_email():
    while True:
        email = fake.email()
        if email not in used_emails:
            used_emails.add(email)
            return email


def escape_sql(s):
    return s.replace("'", "''")


lines = [
    "-- FundBridger seed data (100 records)",
    "-- Generated by seed/seed.py",
    "",
]

records = []
for i in range(NUM_RECORDS):
    user_id = unique_user_id()
    username = unique_username()
    raw_password = fake.password(length=random.randint(12, 16), special_chars=True, digits=True, upper_case=True, lower_case=True)
    password_hash = bcrypt.hashpw(raw_password.encode(), bcrypt.gensalt()).decode()
    email = unique_email()
    status = random.choice(STATUSES)
    role = random.choice(ROLES)

    sql = (
        f"INSERT INTO user_account (\"userID\", username, email, password, \"accountStatus\", role) "
        f"VALUES ({user_id}, '{escape_sql(username)}', '{escape_sql(email)}', "
        f"'{escape_sql(password_hash)}', '{status}', '{role}');"
    )
    records.append(sql)

lines.extend(records)

output_path = os.path.join(os.path.dirname(__file__), "seed_data.sql")
with open(output_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("seed_data.sql generated successfully.")
